name: ZeroM PSVita Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies (git, cmake, etc.)
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake make

    - name: Clone and install vitasdk
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        ./bootstrap-vitasdk.sh
        export VITASDK=/usr/local/vitasdk
        export PATH=$VITASDK/bin:$PATH
        ./install-all.sh

    - name: Build project
      run: |
        export VITASDK=/usr/local/vitasdk
        export PATH=$VITASDK/bin:$PATH
        cd scripts
        sh run_zerom_all.sh
        sh sampleplugin.sh
        
